### ISSUE TITLE
aync set callback with non-ZOK status contains bad data

### ISSUE THREAD

**Issue by lehenbauer** [flightaware/zookeepertcl#7]
If you get ZBADVERSION or something like that then you still get the node status results but they are complete strange and probably pointing to uninitialized memory.  An example appears below.  Probably should not enumerate the status array if the result isn't ZOK.

```
zk ::zk status ZBADVERSION czxid 7810779306726548340 mzxid 2337199356028592221 ctime 8531344264724242800 mtime 2317486274885020773 version 673195558 cversion 538976266 aversion 1634753312 ephemeralOwner 7021232144248086629 dataLength 1528849778 numChildren 1868983913 pzxid 7308331071679066144
```

**Comment by resuna** [comment]
Merged PR#8
